import type { GameRecord } from '../domain/achievement-schema';

export const MOCK_TIMESTAMP = '2026-07-22T00:00:00.000Z';
export const MOCK_TIMESTAMP_2 = '2026-07-22T01:00:00.000Z';

export const mockGameStellarDrift: GameRecord = {
  id: 'stellar-drift',
  title: 'Stellar Drift',
  aliases: ['stellar drift', 'drift'],
  sourceType: 'fictional_demo',
  version: '2026.07.13',
  theme: {
    primary: '#7dd3fc',
    secondary: '#a78bfa',
    surfaceGlow: '#0ea5e9',
    mood: 'neon orbital racing',
  },
  summary: 'Fast sci-fi racer.',
  achievementSets: [
    {
      id: 'stellar-drift-ps',
      platform: 'playstation',
      edition: 'Standard Edition',
      version: '2026.07.13',
      achievements: [
        {
          id: 'sd-ps-001',
          name: 'First Burn',
          description: 'Tutorial race',
          evidence: 'Mandatory',
          reward: { type: 'trophy', grade: 'bronze' },
          tracking: { mode: 'binary' },
          labels: ['story'],
          expectedStage: 'story',
          confidence: 0.99,
          prerequisites: [],
          crossPlatformGroupId: 'group-first-burn',
        },
        {
          id: 'sd-ps-002',
          name: 'Orbit Breaker',
          description: 'Finish Ch 3 shortcut',
          evidence: 'Chapter 3 only',
          reward: { type: 'trophy', grade: 'silver' },
          tracking: { mode: 'binary' },
          labels: ['missable'],
          expectedStage: 'missables',
          confidence: 0.95,
          prerequisites: ['sd-ps-001'],
          spoilerSafeHint: 'Chapter 3 route choice',
          warning: 'Take shortcut before Ch 4',
          crossPlatformGroupId: 'group-orbit-breaker',
        },
        {
          id: 'sd-ps-004',
          name: 'Signal Collector',
          description: 'Recover 48 beacons',
          evidence: 'Free roam',
          reward: { type: 'trophy', grade: 'gold' },
          tracking: { mode: 'counter', unit: 'beacons', target: 48, quickSteps: [1, 5] },
          labels: ['collectible'],
          expectedStage: 'cleanup',
          confidence: 0.98,
          prerequisites: [],
          crossPlatformGroupId: 'group-signal-collector',
        },
        {
          id: 'sd-ps-005',
          name: 'Checklist Mastery',
          description: 'Complete 3 tasks',
          evidence: 'Free roam tasks',
          reward: { type: 'trophy', grade: 'gold' },
          tracking: {
            mode: 'checklist',
            items: [
              { id: 'task-a', name: 'Task A' },
              { id: 'task-b', name: 'Task B' },
              { id: 'task-c', name: 'Task C' },
            ],
          },
          labels: ['grind'],
          expectedStage: 'cleanup',
          confidence: 0.9,
          prerequisites: [],
          spoilerSafeHint: 'Complete required tasks',
        },
        {
          id: 'sd-ps-006',
          name: 'Open Duel Log',
          description: 'Track completed online duels',
          evidence: 'Open-ended activity',
          reward: { type: 'trophy', grade: 'bronze' },
          tracking: { mode: 'counter', unit: 'duels', quickSteps: [1] },
          labels: ['online'],
          expectedStage: 'cleanup',
          confidence: 0.9,
          prerequisites: [],
          warning: 'Online availability can change.',
          spoilerSafeHint: 'An optional online activity tracks completed duels.',
        },
        {
          id: 'sd-ps-007',
          name: 'Spare Binary',
          description: 'A sixth pinnable achievement',
          evidence: 'Fixture coverage',
          reward: { type: 'trophy', grade: 'bronze' },
          tracking: { mode: 'binary' },
          labels: ['story'],
          expectedStage: 'story',
          confidence: 1,
          prerequisites: [],
        },
      ],
    },
    {
      id: 'stellar-drift-steam',
      platform: 'steam',
      edition: 'Standard Edition',
      version: '2026.07.13',
      achievements: [
        {
          id: 'sd-steam-001',
          name: 'First Burn',
          description: 'Tutorial race',
          evidence: 'Mandatory',
          reward: { type: 'achievement' },
          tracking: { mode: 'binary' },
          labels: ['story'],
          expectedStage: 'story',
          confidence: 0.99,
          prerequisites: [],
          crossPlatformGroupId: 'group-first-burn',
        },
      ],
    },
  ],
};

export const mockGameMythHarbor: GameRecord = {
  id: 'myth-harbor',
  title: 'Myth Harbor',
  aliases: ['myth harbor'],
  sourceType: 'fictional_demo',
  version: '2026.07.13',
  theme: {
    primary: '#34d399',
    secondary: '#fbbf24',
    surfaceGlow: '#10b981',
    mood: 'coastal folklore mystery',
  },
  summary: 'Narrative adventure fixture.',
  achievementSets: [
    {
      id: 'myth-harbor-ps',
      platform: 'playstation',
      version: '2026.07.13',
      achievements: [
        {
          id: 'mh-ps-001',
          name: 'Lantern Lit',
          description: 'Light the lantern',
          evidence: 'Mandatory interaction',
          reward: { type: 'trophy', grade: 'bronze' },
          tracking: { mode: 'binary' },
          labels: ['story'],
          expectedStage: 'story',
          confidence: 0.99,
          prerequisites: [],
        },
      ],
    },
  ],
};
